/* Auto-generated by cbindgen — do not edit */

#ifndef SENTRIX_LIBP2P_H
#define SENTRIX_LIBP2P_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct SentrixOption_SentrixRequestCallback SentrixOption_SentrixRequestCallback;

/**
 * Opaque handle to a running SentrixNode.
 */
typedef struct SentrixSentrixHandle SentrixSentrixHandle;

/**
 * Create and start a new SentrixNode.
 *
 * `listen_addr` — multiaddr string, e.g. `/ip4/0.0.0.0/tcp/0`. NULL for default.
 * `handler`     — callback invoked for every incoming AgentRequest. NULL for no handler.
 *
 * Returns an opaque handle, or NULL on error.
 * Free with `sentrix_node_destroy`.
 */
struct SentrixSentrixHandle *sentrix_node_create(const char *listen_addr,
                                                 struct SentrixOption_SentrixRequestCallback handler);

/**
 * Stop and destroy a SentrixNode.
 */
void sentrix_node_destroy(struct SentrixSentrixHandle *handle);

/**
 * Return the node's PeerId as a null-terminated string.
 * Caller must free with `sentrix_free_string`.
 */
char *sentrix_node_peer_id(const struct SentrixSentrixHandle *handle);

/**
 * Return the node's first listen multiaddr as a null-terminated string.
 * Caller must free with `sentrix_free_string`.
 */
char *sentrix_node_multiaddr(const struct SentrixSentrixHandle *handle);

/**
 * Dial a remote peer by multiaddr.
 * Returns 0 on success, -1 on error.
 */
int sentrix_dial(struct SentrixSentrixHandle *handle, const char *multiaddr);

/**
 * Send an AgentRequest JSON to a peer and write the AgentResponse JSON to `response_buf`.
 *
 * `peer_id`      — target peer ID string
 * `request_json` — null-terminated JSON AgentRequest
 * `response_buf` — caller-allocated buffer for the JSON response
 * `response_cap` — capacity of `response_buf` in bytes
 *
 * Returns bytes written (excluding null terminator), or -1 on error.
 */
int sentrix_send(struct SentrixSentrixHandle *handle,
                 const char *peer_id,
                 const char *request_json,
                 char *response_buf,
                 uintptr_t response_cap);

/**
 * Publish a gossip message JSON to the mesh.
 * Returns 0 on success, -1 on error.
 */
int sentrix_gossip_publish(struct SentrixSentrixHandle *handle, const char *message_json);

/**
 * Free a string returned by a sentrix_* function.
 */
void sentrix_free_string(char *s);

#endif /* SENTRIX_LIBP2P_H */
